version: '3'

services:
  virginity-bot-server:
    image: docker.pkg.github.com/virginity-bot/virginitybot/bot:latest
    ports:
      - '8000:8000'
    env_file: virginity-bot.env
    networks:
      - virgin-net
    depends_on:
      - virginity-bot-db
  virginity-bot-cron:
    image: docker.pkg.github.com/virginity-bot/virginitybot/cron:latest
    env_file: virginity-bot.env
    networks:
      - virgin-net
    depends_on:
      - virginity-bot-db
  virginity-bot-db:
    image: postgres:11
    volumes:
      - /var/lib/postgresql/data
    env_file: virginity-bot.env
    networks:
      - virgin-net

networks:
  virgin-net:
