name: Publish Docker

# Controls when the action will run. Triggers the workflow on push or pull
# request events but only for the master branch
on:
  push:
    branches:
      - master
    # Publish `v1.2.3` tags as releases.
    # tags:
    #   - v*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          docker build -f Dockerfile -t bot .
          docker build -f Dockerfile.cron -t cron .

      - name: Login to Registry
        run: |
          echo "${{ secrets. DOCKER_RELEASE_ACCESS_TOKEN }}" | \
          docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Publish to Registry
        run: |
          REPO=$(${{ github.repository }} | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo $REPO
          echo $VERSION

          docker tag bot $REPO/bot:$VERSION
          docker tag cron $REPO/cron:$VERSION

          docker push $REPO/bot:$VERSION
          docker push $REPO/cron:$VERSION
